name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"

permissions:
  contents: read

env:
  GOEXPERIMENT: rangefunc

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run tests
        run: go test -v -timeout 30s -coverprofile=cover.out -covermode=atomic -race ./...

